#!/bin/bash

clear

g++ ./SuperFile.cc \
		../File/TFile.cc \
		../File/TWinFile.cc \
		../Net/TNet.cc \
		../File/platforms/win_file/WinFile.cc \
-l ws2_32 \
-o ../bin/SuperFile.exe

../bin/SuperFile.exe
