#!/bin/bash

clear

g++ ams_test_white.cc \
	AutoMakeProject.cc  \
	AutoMakeSolution.cc \
	../../File/TWinFile.cc \
	../../File/platforms/win_file/WinFile.cc \
-o AutoMakeSolution.exe

./AutoMakeSolution.exe
